# Generated by Django 4.2.5 on 2023-09-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('weight_bottom', models.IntegerField()),
                ('weight_top', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
