# Generated by Django 4.2.5 on 2023-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bear_weight_bottom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bear',
            name='weight_bottom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
