# Generated by Django 4.2.5 on 2023-09-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bear',
            name='food',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
